id: P007931
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 2021-12-17 12:49:58.826518
source_metadata:
  id: bdr:W1KG14523
  title: ཇ་ཤིང་མེ་ཏོག་མ།
  author: ''
  volumes:
    07136b014ffc426ca5d505439ec942d7:
      image_group_id: I1KG15676
      title: Volume 1 of ja shing me tog ma/
      volume_number: 1
      total_pages: 396
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
