id: opecha:P007931
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG14523
  title: ཇ་ཤིང་མེ་ཏོག་མ།
  volume:
    07136b014ffc426ca5d505439ec942d7:
      image_group_id: I1KG15676
      title: Volume 1 of ja shing me tog ma/
      volume_number: 1
      total_pages: 396
  author: ''
ebook_metadata:
  title: ཇ་ཤིང་མེ་ཏོག་མ།
  author: ''
  sku: P007931
  cover: cover.jpg
  layers:
  - pagination
