id: P007931
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG14523
  title: ཇ་ཤིང་མེ་ཏོག་མ།
  author: ''
  volumes:
    497ee761271c4797953b7666c5ea65a0:
      image_group_id: I1KG15676
      title: ''
      volume_number: 1
      total_pages: 396
ebook_metadata:
  title: ཇ་ཤིང་མེ་ཏོག་མ།
  author: ''
  sku: P007931
  cover: cover.jpg
  layers:
  - pagination
